INSERT INTO BOOTS (ID, TYPE, SIZE, MATERIAL, QUANTITY) VALUES (1, 'CHELSEA', 8.0, 'LEATHER', 10);
INSERT INTO BOOTS (ID, TYPE, SIZE, MATERIAL, QUANTITY) VALUES (2, 'CHUKKA', 9.5, 'SUEDE', 25);
INSERT INTO BOOTS (ID, TYPE, SIZE, MATERIAL, QUANTITY) VALUES (3, 'DRESS', 10.0, 'LEATHER', 15);
INSERT INTO BOOTS (ID, TYPE, SIZE, MATERIAL, QUANTITY) VALUES (4, 'CHELSEA', 8.5, 'SUEDE', 20);